// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { SessionProvider } from "@/components/providers/session-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <SessionProvider>{children}</SessionProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next"
import { Inter, Syne } from "next/font/google"
import "./globals.css"
import { SessionProvider } from "@/components/providers/session-provider"

// Body font — clean and readable
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

// Heading font — geometric and bold
const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
})

export const metadata: Metadata = {
  title: "HomeX — Find Properties Across Ghana",
  description:
    "A full-stack real estate platform for browsing, listing, and managing residential properties across Ghana.",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${syne.variable} antialiased`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  )
}